InAl.Etrade/Areas/Customer/Controllers/CardController.cs
using InAl.Etrade.Data;
using InAl.Etrade.Models;
using Iyzipay;
using Iyzipay.Model;
using Iyzipay.Request;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace InAl.Etrade.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class CardController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IEmailSender _emailSender;
        public readonly UserManager<IdentityUser> _userManager;
        [BindProperty()]
        public ShopingCardVM ShopingCardVM { get; set; }





        public CardController(UserManager<IdentityUser> userManager, IEmailSender emailSender, ApplicationDbContext db)
        {
            _db = db;
            _emailSender = emailSender;
            _userManager = userManager;
        }
        public IActionResult Summary()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ShopingCardVM = new ShopingCardVM()
            {
                OrderHeader = new OrderHeader(),
                ListCard = _db.ShopingCards.Where(x => x.ApplicationUserID == claim.Value).Include(y => y.Product)
            };
            foreach (var item in ShopingCardVM.ListCard)
            {
                item.Price = item.Product.Price;
                ShopingCardVM.OrderHeader.OrderTotal += (item.Count * item.Product.Price);

            }
            return View(ShopingCardVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Summary(ShopingCardVM model)
        {

            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ShopingCardVM.ListCard = _db.ShopingCards.Where(x=>x.ApplicationUserID==claim.Value).Include(k=>k.Product);
            ShopingCardVM.OrderHeader.OrderStatus = Other.Durum_Beklemede;
            ShopingCardVM.OrderHeader.ApplicationUserID = claim.Value;
            ShopingCardVM.OrderHeader.OrderDate=DateTime.Now;
            _db.OrderHeader.Add(ShopingCardVM.OrderHeader);
            _db.SaveChanges();
            foreach (var item in ShopingCardVM.ListCard)
            {
                item.Price = item.Product.Price;
                OrderDetails orderDetails = new OrderDetails()
                {
                    ProductID = item.ProductID,
                    OrderID = ShopingCardVM.OrderHeader.ID,
                    Price = item.Price,
                    Count = item.Count
                };
                ShopingCardVM.OrderHeader.OrderTotal += item.Count * item.Product.Price;
                model.OrderHeader.OrderTotal += item.Count * item.Product.Price;
                _db.OrderDetails.Add(orderDetails);
            }
            var payment = PaymentProcess(model);
            _db.ShopingCards.RemoveRange(ShopingCardVM.ListCard);
            _db.SaveChanges();
            HttpContext.Session.SetInt32(Other.ssShoppingCart, 0);
            return RedirectToAction("SiparisTamam");


        }

        private Payment PaymentProcess(ShopingCardVM model)
        {
            Options options = new Options();
            options.ApiKey = "sandbox-CvsZq4DFfOATFNaOxDszCPRqzIQfOpVc";
            options.SecretKey = "sandbox-yp97m4JDMibewDF4EWJk3fKhPYxPrZsb";
            options.BaseUrl = "https://sandbox-api.iyzipay.com";

            CreatePaymentRequest request = new CreatePaymentRequest();
            request.Locale = Locale.TR.ToString();
            request.ConversationId = new Random().Next(1111,9999).ToString();
            request.Price = model.OrderHeader.OrderTotal.ToString();
            request.PaidPrice = model.OrderHeader.OrderTotal.ToString();
            request.Currency = Currency.TRY.ToString();
            request.Installment = 1;
            request.BasketId = "B67832";
            request.PaymentChannel = PaymentChannel.WEB.ToString();
            request.PaymentGroup = PaymentGroup.PRODUCT.ToString();

            //PaymentCard paymentCard = new PaymentCard();
            //paymentCard.CardHolderName = "John Doe";
            //paymentCard.CardNumber = "5528790000000008";
            //paymentCard.ExpireMonth = "12";
            //paymentCard.ExpireYear = "2030";
            //paymentCard.Cvc = "123";
            //paymentCard.RegisterCard = 0;
            //request.PaymentCard = paymentCard;

            PaymentCard paymentCard = new PaymentCard();
            paymentCard.CardHolderName = model.OrderHeader.CartName;
            paymentCard.CardNumber = model.OrderHeader.CartNumber;
            paymentCard.ExpireMonth = model.OrderHeader.ExprationMonth;
            paymentCard.ExpireYear =model.OrderHeader.ExprationYear;
            paymentCard.Cvc = model.OrderHeader.Cvc;
            paymentCard.RegisterCard = 0;
            request.PaymentCard = paymentCard;

            Buyer buyer = new Buyer();
            buyer.Id = model.OrderHeader.ID.ToString();
            buyer.Name = model.OrderHeader.Name;
            buyer.Surname =model.OrderHeader.Surname;
            buyer.GsmNumber = model.OrderHeader.PhoneNumber;
            buyer.Email = "email@email.com";
            buyer.IdentityNumber = "74300864791";
            buyer.LastLoginDate = "2015-10-05 12:43:35";
            buyer.RegistrationDate = "2013-04-21 15:12:09";
            buyer.RegistrationAddress =model.OrderHeader.Address;
            buyer.Ip = "85.34.78.112";
            buyer.City = model.OrderHeader.City;
            buyer.Country = "Turkey";
            buyer.ZipCode = model.OrderHeader.PostalCode;
            request.Buyer = buyer;

            Address shippingAddress = new Address();
            shippingAddress.ContactName = "Jane Doe";
            shippingAddress.City = "Istanbul";
            shippingAddress.Country = "Turkey";
            shippingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            shippingAddress.ZipCode = "34742";
            request.ShippingAddress = shippingAddress;

            Address billingAddress = new Address();
            billingAddress.ContactName = "Jane Doe";
            billingAddress.City = "Istanbul";
            billingAddress.Country = "Turkey";
            billingAddress.Description = "Nidakule Göztepe, Merdivenköy Mah. Bora Sok. No:1";
            billingAddress.ZipCode = "34742";
            request.BillingAddress = billingAddress;

            List<BasketItem> basketItems = new List<BasketItem>();
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //kull.sepetinde olan ürünler getirildi.
            foreach (var item in _db.ShopingCards.Where(x => x.ApplicationUserID == claim.Value).Include(x => x.Product)) 
            {
                basketItems.Add(new BasketItem()
                {
                    Id = item.ID.ToString(),
                    Name = item.Product.Title,
                    Category1 = item.Product.CategoryID.ToString(),
                    ItemType = BasketItemType.PHYSICAL.ToString(),
                    Price=(item.Price*item.Count).ToString()
                }) ;
            }
            request.BasketItems = basketItems;

           return Payment.Create(request, options);
        }

        public IActionResult SiparisTamam()
        {
            return View();
        }
        public IActionResult Index()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            ShopingCardVM = new ShopingCardVM()
            {
                OrderHeader = new OrderHeader(),
                ListCard = _db.ShopingCards.Where(x => x.ApplicationUserID == claim.Value).Include(y => y.Product)
            };
            ShopingCardVM.OrderHeader.OrderTotal = 0;
            ShopingCardVM.OrderHeader.ApplicationUser = _db.ApplicationUsers.FirstOrDefault(k => k.Id == claim.Value);
            foreach (var item in ShopingCardVM.ListCard)
            {
                ShopingCardVM.OrderHeader.OrderTotal += (item.Count * item.Product.Price);

            }
            return View(ShopingCardVM);
        }
        [HttpPost]
        [ActionName("Index")]
        public async Task<IActionResult> IndexPost()
        {
            var claimIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var user = _db.ApplicationUsers.FirstOrDefault(x=>x.Id==claim.Value);
            if (user==null)
            {
                ModelState.AddModelError(string.Empty, "Doğrulama Emaili Boş");
            }
            

            var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
            code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));
            var callbackUrl = Url.Page(
                "/Account/ConfirmEmail",
                pageHandler: null,
                values: new { area = "Identity", userId = user.Id, code = code},
                protocol: Request.Scheme);

            await _emailSender.SendEmailAsync(user.Email, "Confirm your email",
                $"Please confirm your account by <a href='{HtmlEncoder.Default.Encode(callbackUrl)}'>clicking here</a>.");
            ModelState.AddModelError(string.Empty, "Email Doğrulama KodunGönder..");
            return RedirectToAction("Success");

        }
        public IActionResult Success()
        {
            return View();
        }
        public IActionResult Add(int cartID)

InAl.Etrade/Areas/Customer/Views/Card/Index.cshtml
@model ShopingCardVM
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form method="post">
    @if (Model.ListCard.Count() > 0)
    {
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <br />
                    <table id="myTable" class="table table-striped table-bordered">
                        <thead>
                            <tr>
                                <th>
                                    Resim
                                </th>
                                <th>
                                    Başlık
                                </th>
                                <th>
                                    Adet
                                </th>
                                <th>
                                    Fiyat
                                </th>
                                <th>
                                    Tutar
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ListCard)
                            {
                                <tr>
                                    <td>
                                        <img src="@item.Product.Image" width="60" />
                                    </td>
                                    <td>
                                        @item.Product.Title
                                    </td>
                                    <td>
                                        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                                            <div class="btn-group me-2" role="group" aria-label="First group">
                                                <input type="text" style="max-width:45px;" class="form-control" value="@item.Count"/>
                                                <button asp-action="Decrease" asp-route-cartId="@item.ID" class="btn btn-danger"><i class="bi bi-dash-lg"></i></button>
                                                <button asp-action="Add" asp-route-cartId="@item.ID" class="btn btn-primary"><i class="bi bi-plus-lg"></i></button>
                                                <button asp-action="Remove" asp-route-cartId="@item.ID" class="btn btn-danger"><i class="bi bi-trash"></i></button>

                                            </div>

                                        </div>
                                    </td>
                                    <td>
                                        @item.Product.Price.ToString("0.00") ₺
                                    </td>
                                    <td>
                                        @((@item.Count * item.Product.Price).ToString("0.00")) ₺
                                    </td>
                                </tr>
                            }
                            <tr>
                                <td colspan="4" style="text-align:right">
                                    <strong>Toplam Tutar</strong>
                                </td>
                                <td style="background-color:darkred">
                                    <span style="font-size:large; color:white">@Model.OrderHeader.OrderTotal.ToString("0.00") ₺</span>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="row">
                        <div class="col-md-4">
                            <a asp-area="Customer" asp-controller="Home" asp-action="Index" class="btn btn-primary form-control"> Alışverişe Devam Et</a>
                        </div>
                        <div class="col-md-4">

                        </div>
                        <div class="col-md-4">
                            @if (!Model.OrderHeader.ApplicationUser.EmailConfirmed)
                            {
                                <div>
                                    <button type="submit" class="btn btn-warning form-control text-white">Lütfen Email onaylamak için tıklayınız...</button>
                                </div>
                            }
                            else
                            {
                                <a asp-area="Customer" asp-controller="Card" asp-action="Summary" class="btn btn-success form-control">Sipariş Ver</a>
                            }


                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
     <div style="text-align:center;color:red;">Sepetinizde Ürün bulunmamaktadır.</div>
    }

</form>

InAl.Etrade/Areas/Customer/Views/Card/SiparisTamam.cshtml
@{
    ViewData["Title"] = "SiparisTamam";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 style="color:green">Satın aldığınız ürünler en yakın zamanda kargoya verilecektir...</h3>

InAl.Etrade/Areas/Customer/Views/Card/Success.cshtml
@{
    ViewData["Title"] = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Lütfen Adresinizi Kontrol Edin...</h1>

InAl.Etrade/Areas/Customer/Views/Card/Summary.cshtml
@model ShopingCardVM
@{
    ViewData["Title"] = "Summary";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<form  method="post">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-md-6">

                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-3 col-form-label">Adı</label>
                            <div class="col-sm-9">
                                <input type="text" asp-for="OrderHeader.Name" class="form-control">
                                <span asp-validation-for="OrderHeader.Name" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-3 col-form-label">Soyadı</label>
                            <div class="col-sm-9">
                                <input type="text" asp-for="OrderHeader.Surname" class="form-control">
                                <span asp-validation-for="OrderHeader.Surname" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-3 col-form-label">Adres</label>
                            <div class="col-sm-9">
                                <input type="text" asp-for="OrderHeader.Address" class="form-control">
                                <span asp-validation-for="OrderHeader.Address" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-3 col-form-label">Semt</label>
                            <div class="col-sm-9">
                                <input type="text" asp-for="OrderHeader.County" class="form-control">
                                <span asp-validation-for="OrderHeader.County" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-3 col-form-label">Şehir</label>
                            <div class="col-sm-9">
                                <input type="text" asp-for="OrderHeader.City" class="form-control">
                                <span asp-validation-for="OrderHeader.City" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-3 col-form-label">Telefon</label>
                            <div class="col-sm-9">
                                <input type="text" asp-for="OrderHeader.PhoneNumber" class="form-control">
                                <span asp-validation-for="OrderHeader.PhoneNumber" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-3 col-form-label">Posta Kodu</label>
                            <div class="col-sm-9">
                                <input type="text" asp-for="OrderHeader.PostalCode" class="form-control">
                                <span asp-validation-for="OrderHeader.PostalCode" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="col-md-12">

                            <ul class="list-group mb-3">
                                @foreach (var item in Model.ListCard)
                                {
                                    <li class="list-group-item d-flex justify-content-between lh-sm">
                                        <div>
                                            <h6 class="my-0">@item.Product.Title</h6>
                                            <small class="text-muted">@item.Count</small>
                                        </div>
                                        <span class="text-muted">@((item.Count*item.Product.Price).ToString("0.00")) ₺</span>
                                    </li>
                                }

                                <li class="list-group-item d-flex justify-content-between bg-light">
                                    <div class="text-success">
                                        <h6 class="my-0">Toplam Tutar</h6>

                                    </div>
                                    <span class="text-success">@(Model.OrderHeader.OrderTotal.ToString("0.00")) ₺</span>
                                </li>

                            </ul>

                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-4 col-form-label"> kart Adı</label>
                            <div class="col-sm-8">
                                <input type="text" asp-for="OrderHeader.CartName" class="form-control">
                                <span asp-validation-for="OrderHeader.CartName" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label for="inputPassword" class="col-sm-4 col-form-label"> kart Numarası</label>
                            <div class="col-sm-8">
                                <input type="text" asp-for="OrderHeader.CartNumber" class="form-control">
                                <span asp-validation-for="OrderHeader.CartNumber" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="mb-3 row">

                            <div class="col-sm-4">
                                <input type="text" asp-for="OrderHeader.ExprationMonth" class="form-control" placeholder="Ay">
                                <span asp-validation-for="OrderHeader.ExprationMonth" class="text-danger"></span>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" asp-for="OrderHeader.ExprationYear" class="form-control" placeholder="Yıl">
                                <span asp-validation-for="OrderHeader.ExprationYear" class="text-danger"></span>
                            </div>
                            <div class="col-sm-4">
                                <input type="text" asp-for="OrderHeader.Cvc" class="form-control" placeholder="Güvenlik Kodu">
                                <span asp-validation-for="OrderHeader.Cvc" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-md-6">

                    </div>
                    <div class="col-md-6">
                        <button type="submit" class="form-control btn btn-success">Siparişi Tamamla</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{ 

    <partial name="_ValidationScriptsPartial" />
}